const Theme = {
    legend:{
        textStyle:{
            color:'#7188ad'
        }
    },
    title:{
        textStyle:{
            fontSize:14,
            color:'#fff',
            fontWeight:'normal'
        },
        padding:17
    },
    yAxis:{
        axisLine:{
            show:true,
            lineStyle:{
                color:'#5F7292',
                width:1,
                type:'solid'
            }
        },
        axisLabel:{
            textStyle:{
                color:'#7188ad'
            }
        },
        axisTick:{
            show:false,
        },
        splitLine:{
            show:false
        },
        nameTextStyle:{
            color:'#7b7b7b'
        }
    },
    xAxis:{
        axisLine:{
            show:true,
            lineStyle:{
                color:'#5F7292',
                width:1,
                type:'solid'
            }
        },
        axisLabel:{
            textStyle:{
                color:'#7188ad'
            }
        },
        axisTick:{
            show:false,
        },
        splitLine:{
            show:false
        },
        nameTextStyle:{
            color:'#7b7b7b'
        }
    }
}

export default Theme;